server:
  port: ${PORT:8080}

spring:
  mvc:
    locale: es_MX
  datasource:
    url: ${DATABASE_URL:'jdbc:postgresql://localhost:5432/technovationslp'}
    username: postgres
    password: ${DATABASE_PASSWORD:'postgres'}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 2
      max-idle: 1
      min-idle: 1
      initial-size: 1
      test-while-idle: true
      min-evictable-idle-time-millis: 10000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

authentication:
  firebase:
    databaseUrl: ${FIREBASE_DATABASE_URL:}
    configObject: ${FIREBASE_CONFIG:}
  client:
    clientId: ${CLIENT_ID:}
    secret: ${CLIENT_SECRET:}
    accessTokenValiditySeconds: ${ACCESS_TOKEN_VALIDITY_SECONDS:3600}
    refreshTokenValiditySeconds: ${REFRESH_TOKEN_VALIDITY_SECONDS:3600}
    scopes:
      - "read"
      - "write"
  jwt:
    privateKey: ${JWT_PRIVATE_KEY:}
    publicKey: ${JWT_PUBLIC_KEY:}


